from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm


class NewPermissions(models.Model):
    class Meta:
        permissions = [
            ("can_view", "Can view at statistics and outputs generated by the server"),
            ("can_control", "Can control the status of server"),
            ("can_send_pictures",
             "Can send the pictures to the server to be processed by the image classification model"),
        ]


# class MyForm(ModelForm):
#     class Meta:
#         raise NotImplemented("Havent Done Yet :)")
